### ISSUE TITLE
Show component images on the Index.html page 

### ISSUE THREAD

**Issue by connecteev** [kiliman/tailwindui-crawler#13]
Another one (nice to have) that builds on #12 

It would be nice if we could download and show component images on the Index.html page (like the tailwindui.com index page). That would make it easy to (visually) tell what each component is about. 

Examples:
https://tailwindui.com/img/category-thumbnails/sections-heroes.svg
https://tailwindui.com/img/category-thumbnails/sections-pricing.svg
etc

Thanks for considering!

**Comment by kiliman** [comment]
I agree, and I had considered doing that. My concern is that I didn't want to simply "copy" their website. I used the markup (which was similar to what they had in the app shell components), but did not use their images or javascript (for the resizer component).

I suppose I can reach out to Adam and Steve and get permission to use those images.

Thanks for the feedback.

**Comment by connecteev** [comment]
@kiliman of course, happy to share ideas. I mean, in a way, we've already copied the website...thats what scraping is, after all. You're not doing anything illegal because I've seen the TOS and you're not making the work accessible to anyone that hasnt paid for it, but I guess doesn't hurt to check with them.

**Comment by kiliman** [comment]
New v3 simply copies the Tailwind UI site locally (includes all css and javascript), so it works exactly like the online version.

Set `BUILDINDEX=1` and it will be stored in `$OUTPUT/preview`

I do update the index file to link to the remote images, so not downloading those.
