### ISSUE TITLE
Add .env.example file with all possible config options

### ISSUE THREAD

**Issue by connecteev** [kiliman/tailwindui-crawler#14]
This is not an issue for me but thought I'd log it anyway! Adding a .env.example file with all possible config options would make it easier for new users.
It would be nice to have:
- everything pre-configured with defaults (we would leave out the username and password of course!)
- options in the .env.example file commented (like you have on the main github page)

As an aside, only through trial and error did I realize that in order to get the app running and see the index page, you have to cd into the output folder first before you run "serve" / do this: https://github.com/kiliman/tailwindui-crawler#-index-page

**Comment by kiliman** [comment]
Thanks. I try to make the documentation as accessible as possible, but sometimes I take some things for granted. I will make those changes.

As for the index page, I output mine to a separate folder outside of the tailwindui-crawler project, so I already had to change directories, so I guess I didn't think of that.

**Comment by connecteev** [comment]
Your documentation is already amazing. These are simply (small) suggestions for improvement to make it even easier for people new to the repo! Again, thank you!
