### ISSUE TITLE
Integrate with vue-tailwind-prefix-applicator to customize the tailwind prefix

### ISSUE THREAD

**Issue by connecteev** [kiliman/tailwindui-crawler#15]
This is not my idea and it sounds like you've already got the integration with vue-tailwind-prefix-applicator working:
https://github.com/vesper8/vue-tailwind-prefix-applicator/issues/1

Can't wait to have this functionality become available so I can add a prefix to the components automatically. I imagine this will be another transformer and .env configuration option?
Once again thank you!

**Comment by kiliman** [comment]
Yes, I already have the transformer working locally. I hope to push it later today.
