### ISSUE TITLE
[Bug] Crawling seems broken (empty body tags)

### ISSUE THREAD

**Issue by impulse** [kiliman/tailwindui-crawler#27]
HTML output without using any transformer:
```html
<html>
<head /><body /></html>
```

**Comment by kiliman** [comment]
I saw your post on Discord. I tried using your config as well as removing transformers and I got the correct files output. Did you download a release or clone the repo? Let's make sure you have the latest, then we can troubleshoot further. I want to make sure it works for you.

Thanks!

**Comment by impulse** [comment]
Seems to be working now. Maybe there is a latency issue?

**Comment by kiliman** [comment]
I'm not sure what you mean by latency? I simply use `await fetch()` so would assume that it would throw if it timed out. Anyway, let me know if it happens again and we could log the response.

**Comment by benkraus** [comment]
@impulse you don't recall anything you did to get it working, did you? I'm having this exact same problem :(

**Comment by impulse** [comment]
> @impulse you don't recall anything you did to get it working, did you? I'm having this exact same problem :( 

It worked again after a while with no changes. Still not sure where the problem was.

**Comment by kiliman** [comment]
Since I'm scraping an external site, it's possible the Tailwind UI site was having a temporary issue at the time.

**Comment by joveice** [comment]
I have the same issue, have ran it multiple times with and without transformers and all the tags are empty and no code. Just cloned the repo (master).
