### ISSUE TITLE
Blank vue components

### ISSUE THREAD

**Issue by narwy** [kiliman/tailwindui-crawler#33]
```
removed credentials..
OUTPUT=./output
VUE_OUTPUT=./vue
HTMLMODE=alpine|comments
TRANSFORMERS=convertVue
BUILDINDEX=1
```

Is generating blank vue components as:
```
<template>
  
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>
```

**Comment by rodrigobello** [comment]
I believe the `alpine|comments` in `HTMLMODE` means the variable should be either _alpine_ or _comments_, not sure if it's a valid entry.

**Comment by kiliman** [comment]
Yes, true. HTMLMODE should be "alpine" OR "comments"

This determines whether the crawler processes the comments only mode, or uses the "preview" code with the AlpineJS included. For Vue, I would go with alpine, since they are pretty compatible.
