### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir ...

### ISSUE THREAD

**Issue by yabdab** [kiliman/tailwindui-crawler#37]
This ran good the first time, now it fails every time with this error ...

```
% yarn start
yarn run v1.3.2
$ node index.js
🔐  Logging into tailwindui.com...
✅  Success!

🗂   Output is ./output
⏳  Processing /components/marketing/sections/heroes...
🔍  Found 6 components
‼️   { Error: ENOENT: no such file or directory, mkdir './output/components/marketing/sections/heroes'
    at Object.fs.mkdirSync (fs.js:885:18)
    at module.exports.ensureDirExists.dir (/Users/mikeyrab/Projects/tailwindui-crawler/utils.js:23:8)
    at processComponentPage (/Users/mikeyrab/Projects/tailwindui-crawler/index.js:109:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: './output/components/marketing/sections/heroes' }
✨  Done in 1.10s.
```
The output folder is empty.
The dir permissions are 777 so that is not the issue.

**Comment by yabdab** [comment]
Looks like it does not write the directories in order?

**Comment by kiliman** [comment]
Hmm... I just tried it and it worked fine for me. What is your config? Also, what happens if you call 

`mkdir -p ./output/components/marketing/sections/heroes`

The `-p` creates all the intermediate folders like the API call. 

![image](https://user-images.githubusercontent.com/47168/95461233-f868ab00-0943-11eb-93e6-28e795737592.png)

**Comment by yabdab** [comment]
```
EMAIL=******
PASSWORD=*******
OUTPUT=/Users/mikeyrab/Projects/tailwindcss-ui-output
HTMLMODE=alpine
BUILDINDEX=1
TRANSFORMERS=addTailwindCss,prefixSrc,useInter
```

Running mkdir -p works fine

I just added the missing folders manually and the crawler worked without issue.

 ¯\_(ツ)_/¯

**Comment by josephmasongsong** [comment]
Any update on this? I am having the same issue?
Thanks in advance

**Comment by kiliman** [comment]
Looks like it may be a node issue. I'll figure out a workaround. Thanks!

https://github.com/nodejs/node/issues/27293

**Comment by kiliman** [comment]
Cleaning up issues.

I believe this has been resolved. I have not heard of any more complaints.
