### ISSUE TITLE
If you enjoy this project, say thank you!

### ISSUE THREAD

**Issue by pascalandy** [kiliman/tailwindui-crawler#39]
Here is the place to say thank you to folks who are working hard on this project.

« One of the greatest ways to show your appreciation to open source projects you enjoy is to open an issue that let people say thank you »

Disclaimer: I don't have any kind of connexion or personal interest with maintainers(s) of this project. Pure gratitude here.

**Comment by pascalandy** [comment]
So yeah, thank you guys! This rocks and makes me confident about the future of the tailwind ecosystem.

**Comment by kiliman** [comment]
Thanks for the kind comments. 😍

**Comment by pascalandy** [comment]
Closed in favor of https://github.com/kiliman/tailwindui-crawler/issues/9
