### ISSUE TITLE
Crawler hangs on download or throws ETIMEDOUT error

### ISSUE THREAD

**Issue by domipoppe** [kiliman/tailwindui-crawler#41]
Hello,

I have the issue that the crawler randomly stops forever after crawling a couple of components. What is the issue?

![grafik](https://user-images.githubusercontent.com/2047278/104055268-c3901c80-51ee-11eb-95dc-ab8937ff2ab4.png)

Regards,

**Comment by jensolafkoch** [comment]
I have exactly the same problem. At some (very different) point I get an error such as this:

`
⏳  Processing /components/application-ui/headings/page-headings...
‼️   FetchError: request to https://tailwindui.com/components/application-ui/headings/page-headings failed, reason: connect ETIMEDOUT 104.21.24.52:443
    at ClientRequest.<anonymous> (D:\laragon\www\jok-tailwindui-crawler\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
`

Any solutions?


![crawler-01](https://user-images.githubusercontent.com/47628003/116075002-bb22fb00-a692-11eb-9dba-dd02879c14b9.png)

**Comment by kiliman** [comment]
Looks like it is timing out while downloading from Tailwind.

I can add a TIMEOUT option and a RETRY option as well.

**Comment by jensolafkoch** [comment]
I went the hard way and used the workflow option on GitHub, changed the cron job to every minute and downloaded the complete directory - that works for the time being. 

But I guess I won't be the only one experiencing these timeout errors?

Thanks a lot for this package!!

**Comment by kiliman** [comment]
You can update the GitHub action to run on demand.  Add `workflow dispatch:` under the `on:` key.

![image](https://user-images.githubusercontent.com/47168/116094740-cae01680-a675-11eb-8966-c2cee9a753af.png)

Then you can click on Run Workflow.

![image](https://user-images.githubusercontent.com/47168/116094883-e9461200-a675-11eb-8f5f-7d96895f004e.png)

**Comment by jensolafkoch** [comment]
Great, thanks!

**Comment by kiliman** [comment]
@jensolafkoch Can you do me a favor and checkout `features/error-handling` branch?

I added a try/catch around the fetch and some logging. I want to see what the elapsed time from request to error is. That will help me determine what the default timeout value should be.

I ran the crawler on Windows and didn't have an error, so I can't reproduce the problem you're having.

Thanks!

**Comment by jensolafkoch** [comment]
Well, sorry, still the same with this branch ...

`⏳  Processing /components/application-ui/navigation/breadcrumbs...
❌  Error downloading https://tailwindui.com/components/application-ui/navigation/breadcrumbs
Elapsed time 21020ms
FetchError: request to https://tailwindui.com/components/application-ui/navigation/breadcrumbs failed, reason: connect ETIMEDOUT 172.67.217.20:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tailwindui-crawler@3.1.5 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tailwindui-crawler@3.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jok\AppData\Roaming\npm-cache\_logs\2021-04-26T16_18_54_653Z-debug.log`

**Comment by kiliman** [comment]
No, that's what I was expecting. I was just curious how long time timeout was. Seems really odd that you're not getting any response with 21 seconds.

Anyway, I added retry logic, so can you pull latest from that branch and try again.

Thanks!

**Comment by jensolafkoch** [comment]
Does finish now ... thanks again! Glad I could help ... :-)
