### ISSUE TITLE
Preview Header on Safari Broken Height

### ISSUE THREAD

**Issue by rbridge** [kiliman/tailwindui-crawler#42]
Not sure if this would even be the right place for this, but I'm seeing some strange behavior when browsing the index pages for components after generating.

When using Safari there seems to be some really strange behavior going on with the `h-full` class on the vertical spacer.

<img width="1294" alt="Screen Shot 2021-02-12 at 9 13 27 AM" src="https://user-images.githubusercontent.com/916258/107799958-01fb8880-6d13-11eb-8094-f5e6f773149c.png">

When comparing against the elements on the actual TailwindUI site I'm seeing the same classes, but the behavior is correct.

<img width="1294" alt="Screen Shot 2021-02-12 at 9 13 56 AM" src="https://user-images.githubusercontent.com/916258/107800013-16d81c00-6d13-11eb-8f47-ff7d909ab99a.png">

It also seems to be just in Safari, as the local pages look just fine when using Brave.

<img width="1453" alt="Screen Shot 2021-02-12 at 9 18 07 AM" src="https://user-images.githubusercontent.com/916258/107800110-3bcc8f00-6d13-11eb-8cd8-31b6c2566bc4.png">

Any thoughts? I feel like I'm missing something obvious but can't seem to pin it down.

**Comment by kiliman** [comment]
That is very odd. I'm seeing the same behavior.

I tried to re-create the issue on Tailwind Play, but it actually works on Safari there.

https://play.tailwindcss.com/Vuc5NuYq0w

Anyway, I haven't update the crawler in a while. I need to ensure it works properly with TailwindUI v2.x

![image](https://user-images.githubusercontent.com/47168/107811314-f6708780-6d3b-11eb-91d5-745a1ffa7a41.png)

**Comment by rbridge** [comment]
Glad to see I haven't completely lost it. That said it wouldn't be hard to define the height of that element, but just seemed strange that the behavior was inconsistent.
