### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by nichovski** [kiliman/tailwindui-crawler#44]
Hey guys,

Thanks for this amazing project. I'm not able to start it and check it out.  On npm start I'm getting the following error:
![image](https://user-images.githubusercontent.com/1162068/112321945-c60ff780-8cb0-11eb-9947-f4625744c8a2.png)

Any suggestion is appreciated.

Thanks

**Comment by kiliman** [comment]
What version of node are you using? That's a more recent syntax (nullish coalescing operator). You can replace `??` with `||`.

**Comment by nichovski** [comment]
> What version of node are you using? That's a more recent syntax (nullish coalescing operator). You can replace `??` with `||`.

That works. Thanks @kiliman
