### ISSUE TITLE
Update crawler to support new TailwindUI site

### ISSUE THREAD

**Issue by skinnyandbald** [kiliman/tailwindui-crawler#45]
It's previously worked, but ran it today and am getting:

![image](https://user-images.githubusercontent.com/151953/114752227-11537e00-9d24-11eb-9db5-9b69d1320712.png)

hasn't found a single component.

TailwindUI pushed some big updates to their site today, so maybe related to changes they made that broke the crawler? The URL paths seem to still be the same though.

**Comment by kiliman** [comment]
Yes, this is due to the change in site structure due do the new React/Vue components.

I'm working on updating the crawler.

**Comment by kiliman** [comment]
Ok, I've got the initial version crawling the new site. I should have this done tomorrow.

![image](https://user-images.githubusercontent.com/47168/114774729-787e2c00-9d3e-11eb-85bd-0a31ee3b6c79.png)

HTML
![image](https://user-images.githubusercontent.com/47168/114774783-8d5abf80-9d3e-11eb-928c-874c36e0fdd2.png)

React
![image](https://user-images.githubusercontent.com/47168/114774853-a3688000-9d3e-11eb-824f-d4d4f1bfb548.png)

Vue
![image](https://user-images.githubusercontent.com/47168/114774896-b0856f00-9d3e-11eb-80ea-27ad724d8bbb.png)

**Comment by skinnyandbald** [comment]
Ahh cool. Thanks, @kiliman !

**Comment by heychazza** [comment]
Hey @kiliman - using the github action version, and vue doesn't appear for me?

**Comment by kiliman** [comment]
@heychazza Someone else created the GitHub Action and I haven't had a chance to test it out with the new version.

I'll take a look.

**Comment by heychazza** [comment]
> @heychazza Someone else created the GitHub Action and I haven't had a chance to test it out with the new version.
> 
> I'll take a look.

Thank you, tried the crawler locally as well and wasn't able to run..

**Comment by kiliman** [comment]
Just noticed there was a typo in the README. It should be *vue*, not *vuew*. Make sure in the *.env* file it looks like:

```
LANGUAGES=html,react,vue
```

What are you seeing when you run it locally?

**Comment by kiliman** [comment]
Created new issue for GitHub action #46

**Comment by heychazza** [comment]
> Just noticed there was a typo in the README. It should be _vue_, not _vuew_. Make sure in the _.env_ file it looks like:
> 
> ```
> LANGUAGES=html,react,vue
> ```
> 
> What are you seeing when you run it locally?

It only runs html and react.. really odd
