### ISSUE TITLE
Github Action not working

### ISSUE THREAD

**Issue by James4645** [kiliman/tailwindui-crawler#53]
The Github action to crawl and add it to a private repo isn't working. I copied the yml file exactly. I set the secrets for TAILWINDUI_EMAIL and TAILWINDUI_PASSWORD. Two days in a row now the actions tab showed it ran for about 40s but nothing was added to the repo.  

This is what I put in my .env 

LANGUAGES=html,react,vue,alpine
BUILDINDEX=1

**Comment by pngg** [comment]
@James4645  If you're creating a new repository or have updated your default branch from `master`, you will have to specify with [`branch`](https://github.com/GregBrimble/tailwindui-crawler-action/blob/eab4826e59c3011948f7e6f98744d8b8a64e24b8/action.yml#L31) and [`current_branch`](https://github.com/GregBrimble/tailwindui-crawler-action/blob/eab4826e59c3011948f7e6f98744d8b8a64e24b8/action.yml#L27).

   ```diff
   # ...
         - name: Run crawler
           uses: gregbrimble/tailwindui-crawler-action@v1.1.0
           with:
             email: ${{ secrets.TAILWINDUI_EMAIL }}
             password: ${{ secrets.TAILWINDUI_PASSWORD }}
   +         branch: main
   +         current_branch: main
   ```

**Comment by James4645** [comment]
@pngg No, it used Master.

**Comment by kiliman** [comment]
Cleaning up issues.

If you are still having problems with the GitHub Action, please reopen.
