### ISSUE TITLE
Are you sure this package still works?

### ISSUE THREAD

**Issue by Benoit1980** [kiliman/tailwindui-crawler#62]
Hi,

I tried to download the Alpine js versions:
# OUTPUT optional, defaults to ./output
OUTPUT=./output
LANGUAGES=alpine
BUILDINDEX=1

But all the layouts are broken. Any index file I click bring me to "Your file couldn’t be accessedIt may have been moved, edited, or deleted."

And any index.html files with a component brings me to a broken layout.
ERR_FILE_NOT_FOUND
![Screenshot 2022-04-07 224755](https://user-images.githubusercontent.com/6231274/162297938-1e011288-e78a-4537-abef-28db625c9641.jpg)

Thanks

**Comment by kiliman** [comment]
The generated Alpine files are not meant to be viewable as a standalone page.

You need to embed the HTML into your app which has Tailwind CSS and alpine.js already imported.

If you want to "preview" the components locally, then you need to cd into the $OUTPUT/preview folder and run the `serve` command. Then you can view the components as you can on the Tailwind UI web site.

**Comment by Benoit1980** [comment]
Oh I see.. :-) My mistake! Thank you so much!
