### ISSUE TITLE
Does not load the application & ecommerce files on the editor

### ISSUE THREAD

**Issue by Otienoh** [kiliman/tailwindui-crawler#63]
Thanks,
After the last tailwind update when they released the Ecommerce page the theme editor seems to only open the Marketing files. It does not load the application & e-commerce files on the editor.

Yes, I have followed the instructions keenly not sure what I missed because last time it just worked. thanks

<img width="372" alt="image" src="https://user-images.githubusercontent.com/8632640/172070187-4dd1a176-d4f0-47ce-bec0-afa6a208c87d.png">

**Comment by kiliman** [comment]
Thanks I’ll take a look. I’m pretty sure it was working for me. 

Can you post your config (remove your account info of course)?

**Comment by Otienoh** [comment]
Sorry I just realized this was supposed to be a ticket for shuffle 🤦🏾‍♂️

I will close it now and reach out to them via email.

Thanks
