### ISSUE TITLE
419 error on login

### ISSUE THREAD

**Issue by vanenshi** [kiliman/tailwindui-crawler#64]
hey guys, I am getting 419 error on the response from login
any idea how to fix that?

**Comment by lampenmeister** [comment]
Same Problem...

**Comment by vanenshi** [comment]
@kiliman Thank you for this great library
Let me know if I can help you out

**Comment by kiliman** [comment]
I got past the login, but it's not loading the component pages properly (acting as if I'm not logged in). I wonder if they are actively trying to prevent the crawler from working.

They've definitely made some changes that are making it hard to do.

**Comment by kiliman** [comment]
I'm stumped. If I copy the cookies from Chrome Dev Tools and fetch, it works fine. But if I get the cookies from `set-cookie` headers, it fails. Same with cURL. I copy the cookies and it works. But if I use the cookies from the fetch, it fails. 

The cookies look the same, (same format, different values), but it's not working :(

**Comment by kiliman** [comment]
I figured out the issue but working on a solution. I don’t think it was a deliberate block because I’m still able to download if I manually set the required cookies.

**Comment by akoenig** [comment]
@kiliman Good to hear! Thanks for getting back! Can you elaborate a little bit on the workaround?

**Comment by kiliman** [comment]
The problem is that node fetch isn’t getting the entire session cookie value. It only returns about 1070 characters but the actual cookie is around 1400 characters. If I use curl or the browser it gets the full cookie. When I copy+paste that cookie in the crawler it works fine. 

So need to figure out how to get the full cookie value. I’ve tried multiple node packages and they all have the same issue so believe it’s a node platform problem.

**Comment by kiliman** [comment]
Yup, pretty much. Not sure why node can't read the full cookie. I may need to shell out to curl or something else to fetch the cookies.

**Comment by harryowens** [comment]
I'm having the same issue after pasting the cookie - 0 components found. Also using the crawler to try to import components to import into shuffle.dev per their recommendation.

**Comment by kiliman** [comment]
Finally got this problem fixes. They may a lot of changes to the site. In addition to the login issue, they changed how the components are structures.

I also added the ability to download the Page Templates. See the README for details.

Thanks all for your patience.
