### ISSUE TITLE
Not logged in error

### ISSUE THREAD

**Issue by tobyjoiner** [kiliman/tailwindui-crawler#75]
This is what I am getting when I run this.

npm start

> tailwindui-crawler@4.0.1 start
> node index.mjs

🔐  Logging into tailwindui.com...
🔍  Fetching https://tailwindui.com/login
⏱   326ms (200)
✅  Success!

🗂   Output is ./output
🔍  Fetching https://tailwindui.com/components
⏱   687ms (200)
⏳  Processing /components/marketing/sections/heroes...
🔍  Fetching https://tailwindui.com/components/marketing/sections/heroes
⏱   579ms (200)
🚫   Not logged in

**Comment by kiliman** [comment]
Do you have the marketing components in your subscription?

And has this worked for you in the past or is this your first time?

**Comment by tobyjoiner** [comment]
Yes marketing , it's my first time using this.

**Comment by carlosigni** [comment]
Same issue.

**Comment by kiliman** [comment]
Closing this issue. Please re-open if you still have the problem.

**Comment by memeree** [comment]
hi, i am recieving this same error, I am running Yarn in WSL if this matters.
