### ISSUE TITLE
My actions started failing a few days ago, thoughts? I ran it manually with debug

### ISSUE THREAD

**Issue by curlydoodle** [kiliman/tailwindui-crawler#78]
[main] Update tailwindui.com
 145 files changed, 878 insertions(+), 878 deletions(-)
Pushing changes...
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run crawler

**Comment by Taump** [comment]
I have the same error 😔

**Comment by curlydoodle** [comment]
Weird, for the pass 3 days my actions have failed. Today it ran. There were warnings about updating to node 16+

**Comment by kiliman** [comment]
It was happening to me too. I imagine it was an issue with GitHub Actions that they have finally resolved.

**Comment by curlydoodle** [comment]
Ahh if thats the case you can close this issue or wait until more validations happen.
