### ISSUE TITLE
 Not logged in error

### ISSUE THREAD

**Issue by memeree** [kiliman/tailwindui-crawler#80]
unable to re-open issue - raising new one - same issue as the one documented in "Not logged in error #75"
[https://github.com/kiliman/tailwindui-crawler/issues/75](url)

Currently using WSL, Ubuntu

**Comment by kiliman** [comment]
Can you copy and paste the output from the crawler?

Also, do you have all the component libraries or just some?

**Comment by memeree** [comment]
hi kiliman
I have access to all the component libraries.

output is below:
```
yarn run v1.22.19
$ node index.mjs
🔐  Logging into tailwindui.com...
🔍  Fetching https://tailwindui.com/login
⏱   240ms (200)
✅  Success!

🗂   Output is ./output
🔍  Fetching https://tailwindui.com/components
⏱   251ms (200)
⏳  Processing /components/marketing/sections/heroes...
🔍  Fetching https://tailwindui.com/components/marketing/sections/heroes
⏱   297ms (200)
🚫   Not logged in
Done in 1.44s.
```

**Comment by kiliman** [comment]
The crawler verifies you're logged in if it can find your email address in the downloaded HTML. It is case-sensitive as well. Please check that the email you're using in the `.env` file matches what Tailwind UI displays when you're signed in.

https://github.com/kiliman/tailwindui-crawler/blob/d3cc6ee9cf2c87145aa2943ff9c7806e4b80855c/index.mjs#L198-L203

<img width="360" alt="image" src="https://github.com/kiliman/tailwindui-crawler/assets/47168/2ce3e934-d90c-475d-bd36-7d1fca9f3ee0">

**Comment by memeree** [comment]
ah. it was case sensitivity on the email address field - 
I had a capital letter in the account name e.g. `Kiliman@gmail.com` vs. `kiliman@gmail.com`
I updated the account name to reflect all lowercase, and re-ran - works great.

**Comment by kiliman** [comment]
That's great. I should probably update the check to be case-insensitive.
