### ISSUE TITLE
-

### ISSUE THREAD

**Issue by sprightlydev** [kiliman/tailwindui-crawler#81]
-

**Comment by kiliman** [comment]
The other person that had this issue was because the email address they used in the .env file didn't match the one on the Tailwind UI site exactly. It is case-sensitive. So please verify your email.

**Comment by sprightlydev** [comment]
@kiliman Thanks for the quick response, in this case there's no upper-casing in my email. (I reviewed all the issues prior to posting to try to avoid wasting anybody's time.)

I stored the fetched component page from `processComponentPage` and the output shows logged-out and not logged-in status (sign-in and not 'Account' links present), so there's no email in `html` for the script to match as far as I can tell.

**Comment by sprightlydev** [comment]
Does this script still work for others?

I have the latest version of the repo, and get past the "✅  Success!" step but after the 'Output,' 'Processing,' 'Fetching' steps fail with "🚫   Not logged in."

So I'm logged in and debugging the source can verify the above cookies are set, but the viewing the output from `const html = await downloadPage(url)` after saving locally either in a local browser session or directly in a text editor shows that no text 'Account' or my email address showing 'Signed in as' are included. Instead the response shows exactly as the output message describes: a 'Not logged in' state with only sign-in links present.

I have access to all components, but even with only 'application-ui' set it fails in the same way, while trying to fetch the first component of the other set.

If one passes the 'Success' step I'm not sure what other user error could exist, as it is trying to fetch the component set specified in env, so that isn't incorrect either.

**Comment by kiliman** [comment]
Sorry you're still having issues. Can you email me the HTML that gets downloaded? kiliman@gmail.com

**Comment by sprightlydev** [comment]
> Sorry you're still having issues. Can you email me the HTML that gets downloaded? [kiliman@gmail.com](mailto:kiliman@gmail.com)

Hi, thanks again for following up. So I guess it still works for you and others?

I can post the content if you like, but note that but for a newline its content matches the output of the following exactly:

`curl -O https://tailwindui.com/components/application-ui/application-shells/stacked`

If you run that you'll see what the source output is producing, as confirmed by `diff`:

```
    // index.mjs#processComponentPage()
    const html = await downloadPage(url)
    fs.writeFileSync("FETCH", html)
```

When I debugged it I noticed the same--the contents of `html` don't contain any email, so `html.includes(process.env.EMAIL)` fails and generates the error. So I'm authenticating and confirmed the cookies were set in a debug session, but the fetches afterward are failing.

**Comment by kiliman** [comment]
Yes, it's working for me just fine. I'm using it from a GitHub Action to run the crawler each night and update a private repo. This way I can track changes the the library.

What version of node are you using? Perhaps that is the difference.

<img width="620" alt="image" src="https://github.com/kiliman/tailwindui-crawler/assets/47168/eedbd5c6-ab52-406a-8756-0ac07bda80ac">

**Comment by sprightlydev** [comment]
Thanks for confirming.

> What version of node are you using? Perhaps that is the difference.

That's a good idea. I haven't tried a different Node version, am using v18.17.1.

**Comment by kiliman** [comment]
Did you figure out the issue?
