### ISSUE TITLE
not logged in error

### ISSUE THREAD

**Issue by muesli-dev** [kiliman/tailwindui-crawler#84]
I can't download the Tailwind CSS with my credentials. I bought the single dev license and can't download it with this crawler, after the first fetch (login) it says login success after that the next fetch says "not logged in"

**Comment by muesli-dev** [comment]
i found a "simple" fix for the problem.

Replace the parseSetCookieHeaders Function with the following (index.mjs:161):

`function parseSetCookieHeaders(header) {
  let cookies = {}
  const [cookie] = header.split(';')
  const [name, value] = cookie.split('=')
  cookies[name] = decodeURIComponent(value)
  return cookies
}`

Then open your chrome, log in to tailwind ui, open your console (F12), go to network and reload the website.
The first request should contain a cookie with your authentication. Copy all cookie data/text.

![image](https://github.com/kiliman/tailwindui-crawler/assets/101059217/e10846a1-118d-4f9c-8d77-d97c92c1dd21)


Put your cookie into this let like that with "" (index.mjs:74):

![image](https://github.com/kiliman/tailwindui-crawler/assets/101059217/49c39f7e-69aa-4137-9f6f-6621c8a856a7)

Last step is to remove the code that overwrites your set cookie with the first login request.
Remove or comment out the code. (index.mjs:100-104)
![image](https://github.com/kiliman/tailwindui-crawler/assets/101059217/4df1578c-bfa6-4ae2-8a03-eda4ee718b1e)


tad-da! the login is now taken care of by your "stolen" token, and you can fetch the tailwind css.

![image](https://github.com/kiliman/tailwindui-crawler/assets/101059217/f0725ede-c3a7-4d0e-a222-901bdc42d0a2)

**Comment by kiliman** [comment]
Hmm... I'll take a look at the code that is setting headers. I'm wondering if the spread syntax is not working correctly in some cases.

**Comment by sujeetpillai** [comment]
@muesli-dev Thanks for this. I'll test this out on my side
